# Generated by Django 5.0.1 on 2024-02-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0003_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
